### ISSUE TITLE
Fatal: too many params

### ISSUE THREAD

**Issue by turneliusz** [nirvdrum/svn2git#118]
I'm getting that all the time, I believe it's because of lack of escaping of ", how I can fix it?

Running command: git config --local user.name "xxx"
Running command: git config --local user.email "yyy"
Running command: git tag -a -m "blabla "the name" bla" "tag name" "tag path"
fatal: too many params

EDIT:
Seems like https://github.com/nirvdrum/svn2git/blob/master/lib/svn2git/migration.rb

> run_command("git tag -a -m \"#{escape_quotes(subject)}\" \"#{escape_quotes(id)}\" \"#{escape_quotes(tag)}\"")

is not escaping properly. I'm not Ruby guy, anybody with quick-fix?

**Comment by ghost** [comment]
What worked for me, since I was making a Win batch script, was to replace single quotes with double quotes
