### ISSUE TITLE
Allow multiple --branches and --tags options

### ISSUE THREAD

**Issue by gnustavo** [nirvdrum/svn2git#175]
This is a request for improvement, not a bug report.

The git-svn command allows for multiple --branches and --tags options but svn2git allows just one of each. It would be nice to drop this restriction.

I'm sorry, but I can't speak Ruby to provide a pull request. ;-)

**Comment by saulgiordani** [comment]
Hi!

Any news about this?

**Comment by digiguru** [comment]
As I understand it - this tool just uses git-svn behind the scenes - in which case you should be able to pass in multiple branches and tags in the existing --branches and --tags parameters.

`https://git-scm.com/docs/git-svn`

Have you tried that?

**Comment by gnustavo** [comment]
I tried now but it seems that you can only pass a single --branches (or --tags) option and it doesn't accept multiple paths. So, I couldn't make it pass multiple branches/tags to git-svn.

**Comment by saulgiordani** [comment]
I had 2 different folders containing branches, "branches" and "releases".

What I did is to migrate from svn to git 2 times, one passing --branches branches and one passing --branches releases. 

Then I merged one repository into the other.

I know it's a workaround but works.

**Comment by marcelolfilho** [comment]
I guess my problem is the same one of you guys. But in my case I have tons of sub branches...

https://stackoverflow.com/questions/36835012/migrate-svn-branches-subfolders-to-git
