### ISSUE TITLE
svn2git does not have option to create empty svn folders in git

### ISSUE THREAD

**Issue by lvthillo** [nirvdrum/svn2git#248]
I migrate a SVN to a Git repo. The migration went well but when I check folders with `diff` I see the migration ignored the folder of the SVN repo which were empty. I want to create them in Git.

How?

**Comment by lvthillo** [comment]
https://github.com/nirvdrum/svn2git/issues/32

**Comment by pcbeard** [comment]
It would be quite easy to add an option that runs
```
git config svn-remote.svn.preserve-empty-dirs true
git config svn-remote.svn.placeholder-filename .gitignore
```
After the `git svn init` command is performed. I'm pretty sure that's all that `git svn clone --preserve-empty-dirs` is doing.
