### ISSUE TITLE
Use of uninitialized value $u in substitution (s///) at /usr/share/perl5/Git/SVN.pm line 101.

### ISSUE THREAD

**Issue by kenneththorman** [nirvdrum/svn2git#251]
r318 = e960e86877c4d24eeeeb09be0adc9ba742c31040 (refs/remotes/svn/trunk)
Found possible branch point: https://XXX/svn/projectmanage/ProjectManagementDashlets/trunk => https://XXX/svn/projectmanage/ProjectManagementDashlets/branches/Issue2457, 318
Use of uninitialized value $u in substitution (s///) at /usr/share/perl5/Git/SVN.pm line 101.
Use of uninitialized value $u in concatenation (.) or string at /usr/share/perl5/Git/SVN.pm line 101.
refs/remotes/svn/lifo: 'https://XXX/svn/projectmanage/ProjectManagementDashlets' not found in ''

command failed:
git svn fetch

**Comment by kenneththorman** [comment]
Sorry, this seems to be in the SVN.pm perl packages and not in svn2git. Closing this issue and taking it elsewhere.

**Comment by CheatEx** [comment]
Any success finding aright place for the bug? I'm having it one year later.

**Comment by kenneththorman** [comment]
I remember finding a solution to it, but I am afraid that I no longer recall what it was, and I did not document the findings here. I think I found the solution on another posting somewhere and that it was related to adding a few code lines. Sorry that I cannot be of assistance.

**Comment by sp00x** [comment]
This appears to address it:

https://velmuruganv.wordpress.com/2017/06/22/use-of-uninitialized-value-u-in-substitution-s-at-usrshareperl5gitsvn-pm-line-101/

**Comment by legionth** [comment]
Worked for me. Thanks @sp00x 🎉
