### ISSUE TITLE
Hangs on "Error validating server certificate"

### ISSUE THREAD

**Issue by drestuart** [nirvdrum/svn2git#51]
I'm trying to check out from my repo, and svn2git is hanging on this error:

"Error validating server certificate for 'https://www.my.server.org:443':
- The certificate is not issued..." etc.

This message is only printed if I run with the -v flag; without, I get nothing.  In either case, svn2git sits doing nothing (as far as I can tell) and not giving me any feedback.  This should cause svn2git to either quit, or print a reassuring message about how it's forging ahead.

**Comment by saily** [comment]
[drestuart's](https://github.com/nirvdrum/svn2git/issues/51#issuecomment-3906438) workaround works.

**Comment by steveswinsburg** [comment]
Issue still exists. Just keep entering the choice (`t` or `p` followed by _Enter_) over and over till it starts doing something.

**Comment by nirvdrum** [comment]
I can try to fix this again, but git-svn certainly doesn't make it easy :-/

**Comment by steveswinsburg** [comment]
I wouldn't bother, the workaround is cromulent.
