### ISSUE TITLE
Use of uninitialized value $u in substitution (s///) at /usr/lib/git-core/git-svn line 2098

### ISSUE THREAD

**Issue by gfraiteur** [nirvdrum/svn2git#66]
Hi!

I'm trying to import an old and extensive Subversion repository into Git.

I'm using the following command line:

```
svn2git --username gael --notrunk --branches postsharp/branches --notags --verbose https://tygr.kpy.sharpcrafters.com:8443/svn/postsharp
```

It dies with the following output:

``` text
Running command: git svn init --prefix=svn/ --username=gael --no-metadata --branches=postsharp/branches https://tygr.kpy.sharpcrafters.com:8443/svn/postsharp
Running command: git svn fetch 
W: Ignoring error from SVN, path probably does not exist: (160013): Filesystem has no item: File not found: revision 100, path '/postsharp/branches'
W: Do not be alarmed at the above message git-svn is just searching aggressively for old history.
This may take a while on large repositories
Found possible branch point: https://tygr.kpy.sharpcrafters.com:8443/svn/postsharp/postsharp/branches/2.0 => https://tygr.kpy.sharpcrafters.com:8443/svn/postsharp/postsharp/branches/2.0-mdb, 1285
$refname=refs/remotes/svn/1.0
Use of uninitialized value $u in substitution (s///) at /usr/lib/git-core/git-svn line 2098.
Use of uninitialized value $u in concatenation (.) or string at /usr/lib/git-core/git-svn line 2098.
refs/remotes/svn/1.0: 'https://tygr.kpy.sharpcrafters.com:8443/svn/postsharp' not found in ''
```

Would you have an idea of how to work around this issue?

Thanks!

-gael

**Comment by gotdibbs** [comment]
In case anyone else encounters this ... I ran into this issue when a previous run of svn2git failed due to a missing user in our authors.txt file. When running svn2git the second time, it bombed with the aforementioned error. The easiest workaround for me was to recloning the empty git repository I was migrating into.

**Comment by nhinze** [comment]
@gotdibbs that was my issue too.

**Comment by tbowden** [comment]
FWIW, I've also experienced this after a first abortive attempt (missing user "(nobody)" in my authors.txt file).  I ran "rm -rf .git" in the dir I was trying to clone into and it all worked well the second time (after fixing the authors.txt file).  Perhaps a good fix might be to ensure the directory being cloned into is empty before trying to run?
