### ISSUE TITLE
command failed: 2>&1 git checkout -f master

### ISSUE THREAD

**Issue by moreaki** [nirvdrum/svn2git#90]
I must be too dumb for the existing svn2git solutions, since I have started with

http://john.albin.net/git/convert-subversion-to-git

proceeded to

https://github.com/JohnAlbin/git-svn-migrate

and am now trying to import a simple (what appears to be a standard) svn project using your approach with **snv2git**, which quits my attempts with a nonchalant 'command failed':

``` shell
$ svn2git http://apt-cyg.googlecode.com/svn  --verbose
Running command: git svn init --prefix=svn/ --no-metadata --trunk=trunk --tags=tags --branches=branches http://apt-cyg.googlecode.com/svn
Running command: git svn fetch 
Running command: git branch -l --no-color
Running command: git branch -r --no-color
Running command: git config --local --get user.name
Running command: git config --local --get user.email
Running command: git checkout -f master
error: pathspec 'master' did not match any file(s) known to git.
command failed:
2>&1 git checkout -f master
```

The same happens when I invoke the command as follows:

``` shell
$ svn2git http://apt-cyg.googlecode.com/svn/trunk  --verbose
```

Truly, I don't believe a very much simpler svn project can be found to convert; no branches, no tags, no nothing, only a trunk.

**Comment by vmichnowicz** [comment]
Your suggestion worked, thank you @yktoo

**Comment by benson-basis** [comment]
I am hitting this with a standard repo layout:

```
Running command: git svn init --prefix=svn/ --no-metadata --trunk=trunk --tags=tags --branches=branches http://svn.basistech.net/engineering/web-services-common
Initialized empty Git repository in /Users/benson/x/web-services-common/.git/
Using higher level of URL: http://svn.basistech.net/engineering/web-services-common => http://svn.basistech.net/engineering
Running command: git config --local --get user.name
Running command: git config --local svn.authorsfile ~/.svn2git/authors
Running command: git svn fetch
W: Ignoring error from SVN, path probably does not exist: (160013): Filesystem has no item: File not found: revision 100, path '/web-services-common'
W: Do not be alarmed at the above message git-svn is just searching aggressively for old history.
This may take a while on large repositories
Running command: git branch -l --no-color
Running command: git branch -r --no-color
Running command: git config --local --get user.name
Running command: git config --local --get user.email
Running command: git checkout -f master
error: pathspec 'master' did not match any file(s) known to git.
command failed:
git checkout -f master
```

**Comment by nirvdrum** [comment]
@benson-basis What does your repository look like at that point?  It looks like git-svn had some difficulty with the repo at some point.

**Comment by benson-basis** [comment]
I'm really sorry, that was entirely pilot error and a mis-spelled URL that I missed 4 times. I was just about to delete my comment before you got to it.

**Comment by OscarAkaElvis** [comment]
Hi guys, instead of use --rootistrunk which creates to me a "xxx is not a complete URL" issue like @ktalik said... I used --notrunk and worked like a charm.

**Comment by migounette** [comment]
Try to delete the remaining .git (ls -al) and restart.
It works for me.

**Comment by x9t9** [comment]
For me , ( simple , standard tortoise  repos ) , after trying all the options, only @OscarAkaElvis 's solution worked . So thanks.. :-)

**Comment by jamessr2** [comment]
Same boat as x9t9 (also a tortoise repo), notrunk is the only thing that worked

**Comment by standingdreams** [comment]
@jpbonn's solution to remove the .git directory and add `--rootistrunk` worked for me.

**Comment by paulschreiber** [comment]
Running `rm -rf .git` and adding `--rootistrunk` worked for me.

**Comment by penam** [comment]
running rm -rf .git and adding --rootistrunk worked for me too. thanks

**Comment by SergioGomez321** [comment]
running rm -r .git worked for me  thanks.
